# Generated by Django 4.0.6 on 2024-07-28 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquetes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativa',
            name='texto',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='texto',
            field=models.CharField(max_length=200),
        ),
    ]
