# Generated by Django 4.0.6 on 2024-08-16 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enquetes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rotulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Rótulo',
            },
        ),
        migrations.AddField(
            model_name='pergunta',
            name='data_fim',
            field=models.DateField(default='2024-12-31', null=True, verbose_name='Data de encerramento'),
        ),
        migrations.AlterField(
            model_name='alternativa',
            name='quant_votos',
            field=models.IntegerField(default=0, verbose_name='Quantidade de votos'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='data_pub',
            field=models.DateTimeField(verbose_name='Data de publicação'),
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descricao')),
                ('cidade', models.CharField(max_length=40, verbose_name='Cidade')),
                ('pais', models.CharField(max_length=20, verbose_name='País')),
                ('generos', models.TextField(blank=True, null=True, verbose_name='Gêneros')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Autores',
            },
        ),
        migrations.AddField(
            model_name='pergunta',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='enquetes.autor'),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='rotulos',
            field=models.ManyToManyField(to='enquetes.rotulo'),
        ),
    ]
