# Generated by Django 4.0.6 on 2024-08-15 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enquetes', '0002_alter_alternativa_texto_alter_pergunta_texto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rotulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='pergunta',
            name='data_fim',
            field=models.DateField(default='2024-12-31', null=True, verbose_name='Data de Encerramento '),
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='descrição')),
                ('cidade', models.CharField(max_length=40)),
                ('pais', models.CharField(max_length=20, verbose_name='País')),
                ('generos', models.TextField(blank=True, null=True, verbose_name='gêneros')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pergunta',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='enquetes.autor'),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='rotulos',
            field=models.ManyToManyField(to='enquetes.rotulo'),
        ),
    ]
