# Generated by Django 4.0.6 on 2024-08-16 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquetes', '0003_rotulo_pergunta_data_fim_autor_pergunta_autor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'verbose_name_plural': 'autores'},
        ),
        migrations.AlterModelOptions(
            name='rotulo',
            options={'verbose_name': 'rótulo'},
        ),
    ]
