# Generated by Django 4.0.6 on 2024-08-16 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('matricula', models.CharField(max_length=20)),
                ('foto', models.ImageField(upload_to='fotos_alunos')),
            ],
        ),
        migrations.CreateModel(
            name='PEI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateField(auto_now_add=True, verbose_name='criação')),
                ('modificacao', models.DateField(auto_now_add=True, verbose_name='modificação')),
                ('aluno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bazar.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='ServidorNapne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SemestreLetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('periodo', models.IntegerField(verbose_name='período')),
                ('atual', models.BooleanField(default=True)),
                ('pei', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazar.pei')),
            ],
        ),
        migrations.AddField(
            model_name='pei',
            name='operadores',
            field=models.ManyToManyField(to='bazar.servidornapne'),
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
