# Generated by Django 4.2.15 on 2024-09-10 01:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do evento')),
                ('banner', models.ImageField(upload_to='fotos/', verbose_name='Banner')),
                ('data_inicio', models.DateTimeField(verbose_name='Inicio do evento')),
                ('data_fim', models.DateTimeField(null=True, verbose_name='Fim do evento')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('preco', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Preço')),
                ('foto', models.ImageField(upload_to='fotos/', verbose_name='Imagem')),
                ('evento', models.ManyToManyField(to='bazar.evento')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do cliente')),
                ('login', models.CharField(max_length=100, verbose_name='Nome do usuário')),
                ('senha', models.CharField(max_length=20, verbose_name='Senha')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
