# Generated by Django 4.2.15 on 2024-09-10 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bazar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='evento',
        ),
        migrations.AddField(
            model_name='item',
            name='titulo',
            field=models.TextField(blank=True, max_length=30, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='item',
            name='descricao',
            field=models.TextField(max_length=100, verbose_name='Descrição'),
        ),
        migrations.CreateModel(
            name='EventoItem',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('reservado', models.BooleanField(default=False, verbose_name='Reservado')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazar.evento')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazar.item')),
            ],
        ),
    ]
