# Generated by Django 4.2.15 on 2024-09-11 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazar', '0002_remove_item_evento_item_titulo_alter_item_descricao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='titulo',
        ),
        migrations.AddField(
            model_name='evento',
            name='itens',
            field=models.ManyToManyField(related_name='eventos', to='bazar.item'),
        ),
        migrations.DeleteModel(
            name='EventoItem',
        ),
    ]
