# Generated by Django 4.2.15 on 2024-09-11 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazar', '0003_remove_item_titulo_evento_itens_delete_eventoitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='descricao',
            field=models.CharField(max_length=100, verbose_name='Descrição'),
        ),
    ]
