# Generated by Django 4.2.16 on 2024-09-12 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazar', '0004_alter_item_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='descricao',
            field=models.CharField(max_length=60, verbose_name='Descrição'),
        ),
    ]
