# Generated by Django 4.2.15 on 2024-09-13 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bazar', '0005_alter_item_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='itens',
        ),
        migrations.AddField(
            model_name='item',
            name='evento',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bazar.evento'),
        ),
    ]
