# Generated by Django 4.2.15 on 2024-09-13 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazar', '0006_remove_evento_itens_item_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='reservado',
            field=models.BooleanField(default=False, verbose_name='Reservado'),
        ),
    ]
